src/Entity/Session.php
<?php

namespace App\Entity;

use App\Repository\SessionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SessionRepository::class)]
class Session
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $startDate = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $endDate = null;

    #[ORM\Column]
    private ?int $nbPlace = null;

    #[ORM\Column]
    private ?bool $closed = null;

    #[ORM\Column(length: 100)]
    private ?string $name = null;

    /**
     * @var Collection<int, Student>
     */
    #[ORM\ManyToMany(targetEntity: Student::class, inversedBy: 'sessions')]
    private Collection $inscription;

    /**
     * @var Collection<int, Programme>
     */
    #[ORM\OneToMany(targetEntity: Programme::class, mappedBy: 'session')]
    private Collection $programmes;

    #[ORM\ManyToOne(inversedBy: 'sessions')]
    private ?Formation $formation = null;

    #[ORM\ManyToOne(inversedBy: 'referent')]
    private ?Formateur $formateur = null;


    public function __construct()
    {
        $this->inscription = new ArrayCollection();
        $this->programmes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): static
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): static
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getNbPlace(): ?int
    {
        return $this->nbPlace;
    }

    public function setNbPlace(int $nbPlace): static
    {
        $this->nbPlace = $nbPlace;

        return $this;
    }

    public function isClosed(): ?bool
    {
        return $this->closed;
    }

    public function setClosed(bool $closed): static
    {
        $this->closed = $closed;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function __toString() {
        return $this->name;
    }

    /**
     * @return Collection<int, Student>
     */
    public function getInscription(): Collection
    {
        return $this->inscription;
    }

    public function addInscription(Student $inscription): static
    {
        if (!$this->inscription->contains($inscription)) {
            $this->inscription->add($inscription);
        }

        return $this;
    }

    public function removeInscription(Student $inscription): static
    {
        $this->inscription->removeElement($inscription);

        return $this;
    }

    /**
     * @return Collection<int, Programme>
     */
    public function getProgrammes(): Collection
    {
        return $this->programmes;
    }

    public function addProgramme(Programme $programme): static
    {
        if (!$this->programmes->contains($programme)) {
            $this->programmes->add($programme);
            $programme->setSession($this);
        }

        return $this;
    }

    public function removeProgramme(Programme $programme): static
    {
        if ($this->programmes->removeElement($programme)) {
            // set the owning side to null (unless already changed)
            if ($programme->getSession() === $this) {
                $programme->setSession(null);
            }
        }

        return $this;
    }

    public function getFormation(): ?Formation
    {
        return $this->formation;
    }

    public function setFormation(?Formation $formation): static
    {
        $this->formation = $formation;

        return $this;
    }

    public function nbStudent() {
        $student = count($this->inscription);

        return $student;
    }

    public function nbAvailable() {
        $student = count($this->inscription);
        $nbSlot = $this->nbPlace - $student;

        return $nbSlot;
    }

    public function getSessionStart() {
        $now = new \DateTime();
        $interval = $this->startDate->diff($now);
        return $interval->format("%Y%m%d");
    }

    public function getVerifDate($startDate, $endDate) {
        $now = new \DateTime();

        if ($now < $startDate) {
            if ($startDate < $endDate) {
                return true;
            } else {
                return false;
            }
        } else {
            return false;
        }
    }

    public function getEnCours() {
        $now = new \DateTime();

        if ($now > $this->startDate && $now < $this->endDate) {
            return true;
        } else {
            return false;
        }
    }

    public function getProchainement() {
        $now = new \DateTime();

        if ($now < $this->startDate) {
            return true;
        } else {
            return false;
        }
    }

    public function getTerminer() {
        $now = new \DateTime();

        if ($now > $this->endDate) {
            return true;
        } else {
            return false;
        }
    }

    public function getFormateur(): ?Formateur
    {
        return $this->formateur;
    }

    public function setFormateur(?Formateur $formateur): static
    {
        $this->formateur = $formateur;

        return $this;
    }
}

src/Controller/PersonneController.php
<?php

namespace App\Controller;

use App\Entity\Student;
use App\Entity\Formateur;
use App\Form\StudentType;
use App\Form\FormateurType;
use App\Repository\StudentRepository;
use App\Repository\FormateurRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use MercurySeries\FlashyBundle\FlashyNotifier;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class PersonneController extends AbstractController
{
    #[Route('/personne', name: 'app_personne')]
    public function index(StudentRepository $studentRepository): Response
    {
        $user = $this->getUser();

        if ($user) {

        $students = $studentRepository->findBy([], ['name' => 'ASC']);

        
        return $this->render('personne/index.html.twig', [
            'controller_name' => 'PersonneController',
            'students' => $students,
        ]);

        }
        else {
            return $this->redirectToRoute('app_login');
        }
    }

    // Method pour l'affichage des formateurs
    #[Route('/formateur', name: 'app_formateur')]
    public function listeFormateurs(FormateurRepository $formateurRepository): Response
    {
        $user = $this->getUser();

        if ($user) {

        $formateurs = $formateurRepository->findBy([], ['name' => 'ASC']);

        
        return $this->render('personne/list_formateur.html.twig', [
            'controller_name' => 'PersonneController',
            'formateurs' => $formateurs,
        ]);

        }
        else {
            return $this->redirectToRoute('app_login');
        }
    }

    // Method pour AJOUTER ou EDIT un STAGIAIRE
    #[Route('/personne/new', name: 'new_student')]
    #[Route('/personne/{id}/edit', name: 'edit_student')]
    public function new_editStudent(StudentRepository $studentRepository, Student $student = null, Request $request, EntityManagerInterface $entityManager, FlashyNotifier $flashy, $id = null): Response 
    {

        $user = $this->getUser();

        if ($user) {

        // Si il n'y a pas de STAGIAIRE,
        if (!$student) {
            // On crée un nouvel objet STAGIAIRE
            $student = new Student();
        } else {
            $student = $studentRepository->find($id);
        }
        
        
        // On crée le formulaire pour le STAGIAIRE
        $form = $this->createForm(StudentType::class, $student);
                
        $form->handleRequest($request);
                
        
        // Si le formulaire est submit
        if ($form->isSubmitted() && $form->isValid()) {
                    
            // On recupère les données du formulaire
            $student = $form->getData();
        
            // PREPARE PDO
            $entityManager->persist($student);
            // EXECUTE PDO
            $entityManager->flush();
        
            // Puis on redirige l'user vers la liste des STAGIAIRE
            $flashy->info("Formulaire validé avec succès ✓", "");
            return $this->redirectToRoute('app_personne');
        }
                
        return $this->render('personne/newStudent.html.twig', [
            'formAddStudent' => $form,
            'student' => $student,
            'edit' => $student->getId()
        ]);

        }
        else {
            return $this->redirectToRoute('app_login');
        }
    }

    // Method pour ajoutés un formateur ou pour l'EDIT
    #[Route('/formateur/new', name: 'new_formateur')]
    #[Route('/formateur/{id}/edit', name: 'edit_formateur')]
    public function new_editFormateur(FormateurRepository $formateurRepository, Formateur $formateur = null, Request $request, EntityManagerInterface $entityManager, FlashyNotifier $flashy, $id = null): Response 
    {

        $user = $this->getUser();

        if ($user) {

        // Si il n'y a pas de FORMATEUR,
        if (!$formateur) {
            // On crée un nouvel objet FORMATEUR
            $formateur = new Formateur();
        } else {
            $formateur = $formateurRepository->find($id);
        }
        
        
        // On crée le formulaire pour le FORMATEUR
        $form = $this->createForm(FormateurType::class, $formateur);
                
        $form->handleRequest($request);
                
        
        // Si le formulaire est submit
        if ($form->isSubmitted() && $form->isValid()) {
                    
            // On recupère les données du formulaire
            $formateur = $form->getData();
        
            // PREPARE PDO
            $entityManager->persist($formateur);
            // EXECUTE PDO
            $entityManager->flush();
        
            // Puis on redirige l'user vers la liste des FORMATEUR
            $flashy->info("Formulaire validé avec succès ✓", "");
            return $this->redirectToRoute('app_formateur');
        }
                
        return $this->render('personne/newFormateur.html.twig', [
            'formAddFormateur' => $form,
            'formateur' => $formateur,
            'edit' => $formateur->getId()
        ]);

        }
        else {
            return $this->redirectToRoute('app_login');
        }
    }

    // Method pour supprimer un stagiaire
    #[Route('/student/{id}/delete', name: 'delete_student')]
    public function delete(Student $student, EntityManagerInterface $entityManager, FlashyNotifier $flashy)
    {
        $user = $this->getUser();

        if ($user) {
        // Permet la suppression d'un stagiaire (delete from)
        $entityManager->remove($student);
        $entityManager->flush();

        // Puis on redirige l'user vers la liste des stagiaire
        $flashy->info("Stagiaire supprimé avec succès ✓", "");
        return $this->redirectToRoute('app_personne');

        }
        else {
            return $this->redirectToRoute('app_login');
        }
    }

    // Method pour supprimer un formateur
    #[Route('/formateur/{id}/delete', name: 'delete_formateur')]
    public function deleteFormateur(Formateur $formateur, EntityManagerInterface $entityManager, FlashyNotifier $flashy)
    {
        $user = $this->getUser();

        if ($user) {
        // Permet la suppression d'un stagiaire (delete from)
        $entityManager->remove($formateur);
        $entityManager->flush();

        $flashy->info("Formateur supprimé avec succès ✓", "");
        // Puis on redirige l'user vers la liste des formateurs
        return $this->redirectToRoute('app_formateur');

        }
        else {
            return $this->redirectToRoute('app_login');
        }
    }

    // Method pour afficher le detail d'un stagiaire
    #[Route('/student/{id}', name: 'show_student')]
    public function showFormation(StudentRepository $studentRepository, $id): Response 
    {
        $user = $this->getUser();

        if ($user) {
        
        $student = $studentRepository->find($id);

        if ($student) {
    
            return $this->render('personne/showStudent.html.twig', [
                'student' => $student
            ]);

        } else {
            return $this->redirectToRoute('app_personne');
        }

        }
        else {
            return $this->redirectToRoute('app_login');
        }

    }

    // Method pour afficher le detail d'un formateur
    #[Route('/formateur/{id}', name: 'show_formateur')]
    public function showFormateur(FormateurRepository $formateurRepository, $id): Response 
    {
        $user = $this->getUser();

        if ($user) {
        
        $formateur = $formateurRepository->find($id);

        if ($formateur) {
    
            return $this->render('personne/showFormateur.html.twig', [
                'formateur' => $formateur
            ]);

        } else {
            return $this->redirectToRoute('app_formateur');
        }

        }
        else {
            return $this->redirectToRoute('app_login');
        }

    }


    
}

templates/personne/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste Stagiaires{% endblock %}

{% block titlePage %} <h1> STAGIAIRE </h1> {% endblock %}


{% block body %}

<div class="contentListStudent">

    <div class="title_page">
        <h1> Liste des stagiaires </h1>
        <hr class="after_title" />
    </div>
        
{% if students %}
    
<div class="boxListStudent">
<div class="tableStudent">
<h2>Stagiaires</h2>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Nom - Prénom</th>
            <th scope="col">Ville</th>
            <th scope="col">Email</th>
            <th scope="col">Téléphone</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
            {% for student in students %}
                <tr>
                    <td scope="row"><a href="{{ path('show_student', {id: student.id}) }}"> {{ student.lastName|upper }} {{ student.name }} </a> </td>
                    <td>{{ student.city }}</td>
                    <td>{{ student.email }}</td>
                    <td>{{ student.phoneNumber }}</td>
                    <td><button type="button"  class="buttonModal deleteListStudent" data-id="{{ student.id }}" data-entity="student" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                        DEL
                      </button>
                        </td>
                </tr>
            {% endfor %}
        
            <tr>
                <td scope="row"></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>

    </tbody>
</table>

<a href="{{ path('new_student') }}" class="addStudent"> Ajouter un stagiaire </a>

</div>
</div>

{% else %}

<p> no student currently</p>
{% endif %}


{% endblock %}

templates/personne/list_formateur.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste Formateur{% endblock %}

{% block titlePage %} <h1> FORMATEUR </h1> {% endblock %}


{% block body %}

{% if formateurs %}
    

<div class="contentListStudent">

    <div class="title_page">
        <h1> Liste des formateurs </h1>
        <hr class="after_title" />
    </div>

<div class="boxListStudent">
    <div class="tableFormateur">
        <h2>Formateur</h2>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Nom - Prénom</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                    {% for formateur in formateurs %}
                        <tr>
                            <td scope="row"><a href="{{ path('show_formateur', {id: formateur.id})}}"> {{ formateur.lastName|upper }} {{ formateur.name }} </a> </td>
                                <td><button type="button"  class="buttonModal deleteListStudent" data-id="{{ formateur.id }}" data-entity="formateur" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                                    DEL
                                  </button></td>
                        </tr>
                    {% endfor %}
                
                    <tr>
                        <td scope="row"></td>
                        <td></td>
                    </tr>
        
            </tbody>
        </table>

        <a href="{{ path('new_formateur') }}" class="addStudent"> Ajouter un formateur </a>
    </div>
</div>

{% else %}

<p> no formateurs currently</p>
{% endif %}


{% endblock %}

templates/personne/newFormateur.html.twig
{% extends 'base.html.twig' %}

{% block title %}Add Student{% endblock %}

{% block titlePage %} <h1> STAGIAIRE </h1> {% endblock %}

{% block body %}

<section class="contentFormStudent">


    {% if edit %}
    <div class="title_page">
        <h1> Edit {{ formateur }} </h1>
        <hr class="after_title" />
    </div>
    {% else %}
    <div class="title_page">
        <h1> Ajout formateur</h1>
        <hr class="after_title" />
    </div>
    {% endif %}

    <div class="formStudent">
        <div class="boxFormStudent">
            <h1><span class="blue">FORMATEUR</span></h1>
    {{ form_start(formAddFormateur) }}

    <div class="formsError">
        <div class="row">
            <div class="col-sm">
                {{ form_row(formAddFormateur.lastName) }}
            </div>
            <div class="col-sm">
                {{ form_row(formAddFormateur.name) }}
            </div>
        </div>

        {{ form_row(formAddFormateur.valider) }}
        </div>
    </div>
    </div>

{{ form_end(formAddFormateur) }}

<p class="champObligatoire">* Champ obligatoire</p>
</section>
{% endblock %}

templates/personne/newStudent.html.twig
{% extends 'base.html.twig' %}

{% block title %}Add Student{% endblock %}

{% block titlePage %} <h1> STAGIAIRE </h1> {% endblock %}

{% block body %}

<section class="contentFormStudent">


    {% if edit %}
    <div class="title_page">
        <h1> Edit {{ student }} </h1>
        <hr class="after_title" />
    </div>
    {% else %}
    <div class="title_page">
        <h1> Ajout Stagiaire </h1>
        <hr class="after_title" />
    </div>
    {% endif %}

    <div class="formStudent">
        <div class="boxFormStudent">
            <h1><span class="blue">STAGIAIRE</span></h1>
    {{ form_start(formAddStudent) }}

    <div class="formsError">
        <div class="row">
            <div class="col-sm">
                {{ form_row(formAddStudent.name) }}
            </div>
            <div class="col-sm">
                {{ form_row(formAddStudent.lastName) }}
            </div>
        </div>

        {{ form_row(formAddStudent.birthday) }}

        <div class="row">
            <div class="col-sm">
                {{ form_row(formAddStudent.city) }}
            </div>
            <div class="col-sm">
                {{ form_row(formAddStudent.sexe) }}
            </div>
        </div>

        <div class="row">
            <div class="col-sm">
                {{ form_row(formAddStudent.email) }}
            </div>
            <div class="col-sm">
                {{ form_row(formAddStudent.phoneNumber) }}
            </div>
        </div>

        {{ form_row(formAddStudent.valider) }}
        </div>
    </div>
    </div>
    
{{ form_end(formAddStudent) }}

<p class="champObligatoire">* Champ obligatoire</p>
</section>
{% endblock %}

templates/personne/showFormateur.html.twig
{% extends 'base.html.twig' %}

{% block title %}Detail Formateur{% endblock %}

{% block titlePage %} <h1> FORMATEUR </h1> {% endblock %}

{% block body %}

<div class="contentDetStudent">

<div class="title_page">
    <h1> {{ formateur.lastName|upper }} {{ formateur.name }} </h1>
    <hr class="after_title" />
</div>

<div class="cardStudent">

    <div class="boxStudent">
        <div class="title">
            <h3><u><strong>Information</strong></u></h3>
            <div class="actionStudent">
                <a href="{{ path('edit_formateur', {id: formateur.id}) }}" class="editStudent"> Edit </a>
                <button type="button"  class="buttonModal deleteListModule" data-id="{{ formateur.id }}" data-entity="formateur" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                    DEL
                  </button>            </div>
        </div>

        <div class="infoStudent">
            <p><strong>Nom : </strong> {{ formateur.lastName|upper }} </p>
            <p><strong>Prénom : </strong> {{ formateur.name }}</p>

            <h3><u><strong>Référent formation :</strong></u></h3>

            <ul>
                {% for session in formateur.getReferent() %}
                    <li>
                        <a href="{{ path('show_formation', {id: session.id}) }}">
                            {{ session.formation.name }} 
                        </a><br> 
                        <span class="dateFormation">
                            (du {{ session.startDate|date('Y-m-d') }} au {{ session.endDate|date('Y-m-d') }})

                                {% if session.enCours %}
                                    <strong>> En cours</strong>
                                {% elseif session.prochainement %}
                                    <strong>> Non commencée</strong>
                                {% else %}
                                    <strong>> Terminée</strong>
                                {% endif %}
                                
                        </span>
                    </li><br>
                {% endfor %}
            </ul>
        </div>
    </div>


</div>

</div>
{% endblock %}

templates/personne/showStudent.html.twig
{% extends 'base.html.twig' %}

{% block title %}Detail Stagiaire{% endblock %}

{% block titlePage %} <h1> STAGIAIRE </h1> {% endblock %}

{% block body %}

<div class="contentDetStudent">

<div class="title_page">
    <h1> {{ student.lastName|upper }} {{ student.name }} </h1>
    <hr class="after_title" />
</div>

<div class="cardStudent">

    <div class="boxStudent">
        <div class="title">
            <h3><u><strong>Information</strong></u></h3>
            <div class="actionStudent">
                <a href="{{ path('edit_student', {id: student.id}) }}" class="editStudent"> Edit </a>
                <button type="button" class="buttonModal deleteListModule" data-id="{{ student.id }}" data-entity="student" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                    Delete
                  </button>
            </div>
        </div>

        <div class="infoStudent">
            <p><strong>Sexe : </strong> {{ student.sexe }} </p>
            <p><strong>Date de naissance : </strong> {{ student.birthday|date("d/m/Y") }} ({{ student.Age }} ans)</p>
            <p><strong>Ville : </strong> {{ student.city }} </p>
            <p><strong>Email : </strong> {{ student.email }} </p>
            <p><strong>Téléphone : </strong> {{ student.phoneNumber }} </p>

            <h3><u><strong>Formation prévues / en cours</strong></u></h3>

            <ul>
                {% for session in student.Sessions %}
                    <li>
                        
                        <button type="button"  class="buttonModalDelStagiaire deleteListStudent" data-idsession="{{ session.id }}" data-idstudent="{{ student.id }}" data-entity="session" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                            DEL
                          </button>
                        <a href="{{ path('show_formation', {id: session.id}) }}">
                            
                            {# <a href="{{ path('del_StudentSession', {sessionId: session.id, studentId: student.id, returnStudent: true}) }}" title="desinscrire Stagiaire"><i class="fa-solid fa-x red"></i></a>  #}

                              {{ session.formation.name }}
                        </a><br> 
                        <span class="dateFormation">
                            (du {{ session.startDate|date('d-m-Y') }} au {{ session.endDate|date('d-m-Y') }})
                                {% if session.enCours %}
                                    <strong>> En cours</strong>
                                    {% elseif session.prochainement %}
                                    <strong>> Non commencée</strong>
                                    {% else %}
                                    <strong>> Terminée</strong>
                                {% endif %}
                                
                        </span>
                    </li><br>
                {% endfor %}
            </ul>
        </div>
    </div>


</div>

</div>
{% endblock %}